# Generated by Django 4.2.5 on 2023-09-20 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_delete_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_training', models.DateField()),
                ('training_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.trainingprogram')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='panel.company')),
            ],
        ),
    ]
