# Generated by Django 4.2.3 on 2023-09-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_rename_company_typeid_company_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
