# Generated by Django 4.2.5 on 2023-09-20 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
