# Generated by Django 4.2.3 on 2023-09-18 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_company_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='trainer',
        ),
        migrations.AddField(
            model_name='request',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='panel.company'),
        ),
    ]
