# Generated by Django 4.2.2 on 2023-07-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourtrainer',
            name='profile_image',
            field=models.ImageField(upload_to='static/frontend/images/'),
        ),
    ]
