# Generated by Django 4.2.2 on 2023-07-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_ourtrainer_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourtrainer',
            name='profile_image',
            field=models.ImageField(upload_to='frontend/static/frontend/images/'),
        ),
    ]
